-- Limpieza de Paquetes
BEGIN
   EXECUTE IMMEDIATE 'DROP PACKAGE PKG_MEDICO';
   EXECUTE IMMEDIATE 'DROP PACKAGE PKG_PACIENTE';
   -- EXECUTE IMMEDIATE 'DROP PACKAGE PKG_CITA';
EXCEPTION
   WHEN OTHERS THEN 
      NULL; -- Ignora el error si el paquete no existe
END;
/