spring.application.name=clinica-api

server.port=8082

spring.datasource.url=jdbc:oracle:thin:@192.168.56.101:1521/ORCL
spring.datasource.username=system
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# A�ade esto para evitar que JPA intente crear tablas autom�ticamente 
# y choque con tus scripts manuales
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
